server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
         #url del repo donde están los proyectos
         uri: https://github.com/jmcoca/NTTjmcoca.git
         #donde estan los archivos de confi
         searchPaths: config-data


spring.servlet.multipart.max-file-size:
  5MB
spring.servlet.multipart.max-request-size:
    5MB
